# Generated by Django 2.2.4 on 2019-08-30 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(help_text='Ingrese el idioma natural del libro (por ejemplo, inglés, francés, japonés, etc.)', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='idioma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Idioma'),
        ),
    ]
