# Generated by Django 2.2.4 on 2019-08-30 01:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190829_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='name',
            field=models.CharField(help_text='Ingrese el nombre del género (p. ej. Ciencia Ficción, Poesía Francesa etc.).', max_length=200),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='idioma',
            field=models.CharField(help_text='Ingrese el idioma natural del libro (por ejemplo, inglés, francés, japonés, etc.).', max_length=200),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.ManyToManyField(help_text='Seleccione un genero para este libro.', to='catalog.Genero'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='resumen',
            field=models.TextField(help_text='Ingrese un breve resumen del libro.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='librocopia',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID único para este libro particular en toda la biblioteca.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='librocopia',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Disponibilidad del libro.', max_length=1),
        ),
        migrations.AlterField(
            model_name='mymodelname',
            name='my_field_name',
            field=models.CharField(help_text='Enter field documentation.', max_length=20),
        ),
    ]
